{
 "title": "Windows Events",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "Event_ID", "label": "Event id", "query": "select eventid from $table" },
   { "name": "count", "label": "less then", "query": "1000" },
   {
    "name": "table",
    "label": "Table",
    "query": "SystemWarnings, SystemErrors, SystemCriticals, ApplicationsWarnings, ApplicationsErrors"
   },
   { "name": "exceptionEvent", "label": "without event", "query": "0" },
   { "name": "exceptid2", "label": "and without event", "query": "0" }
  ]
 },
 "panels": [
  {
   "title": "Event Description ($table)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  -- $__timeEpoch(<time_column>),\n  -- <value column> as value,\n  eventid,\n  machine,\n  description,\n  count,\n  datentime\nFROM\n  $table\nWHERE\n  -- $__timeFilter(time_column)\n  eventid = $Event_ID\nORDER BY datentime, count\n-- ORDER BY\n  -- <time_column> ASC"
    }
   ]
  },
  {
   "title": "Total System Errors (by single event) $table",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeEpoch(datentime),\r\n  count as value,\r\n  eventid as metric\r\nFROM \r\n  $table\r\nWHERE\r\n  $__timeFilter(datentime)\r\n  and eventid = $Event_ID\r\nGROUP BY eventid, count, datentime\r\nORDER BY datentime ASC"
    },
    {
     "rawSql": "SELECT \r\n  $__timeEpoch(datentime),\r\n  count(machine) as value,\r\n  eventid as metric\r\nFROM $table\r\nWHERE \r\n  $__timeFilter(datentime)\r\n  and eventid = $Event_ID\r\nGROUP BY eventid, datentime\r\nORDER by datentime ASC"
    }
   ]
  },
  {
   "title": "Total SystemErrors  (Machines) $table",
   "type": "graph",
   "description": "count of events, which happened at least once on the different machines",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeEpoch(datentime),\r\n  count(machine) as value,\r\n  eventid as metric\r\nFROM $table\r\nWHERE \r\n  $__timeFilter(datentime)\r\n  AND eventid != $exceptionEvent\r\n  AND eventid != $exceptid2\r\nGROUP BY eventid, datentime\r\nORDER by datentime ASC"
    }
   ]
  },
  {
   "title": "Events (total count) $table",
   "type": "graph",
   "description": "Total count of all events in specified period for all machines",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  -- TOP(20)\n  $__timeEpoch(datentime),\n  count as value,\n  eventid as metric\nFROM\n  $table\nWHERE\n  $__timeFilter(datentime)\n  AND count < $count\n  AND eventid != $exceptionEvent\n  AND eventid != $exceptid2\nGROUP BY eventid, datentime, count\nORDER BY datentime DESC\n"
    }
   ]
  },
  {
   "title": "Total Events Count (Machines) $table",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeEpoch(datentime),\r\n  count(machine) as value,\r\n  eventid as metric\r\nFROM $table\r\nWHERE \r\n  $__timeFilter(datentime)\r\nGROUP BY eventid, datentime\r\nORDER by datentime ASC"
    }
   ]
  },
  {
   "title": "Total Events Count $table",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeEpoch(datentime),\r\n  count as value,\r\n  eventid as metric\r\nFROM \r\n  $table\r\nWHERE\r\n  $__timeFilter(datentime)\r\n  and count < $count\r\n  AND eventid != $exceptionEvent\r\n  AND eventid != $exceptid2\r\nGROUP BY eventid, count, datentime\r\nORDER BY datentime ASC"
    }
   ]
  }
 ]
}